site_name: My Docs
site_url: https://zyrethor.github.io/rklcs
docs_dir: docs
use_directory_urls: false
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: slate  
  font:
    text: Roboto
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.select
    - search.suggest
    - toc.integrate
    - navigation.top

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.arithmatex:
      generic: true
      tex_inline_wrap: ['$', '$']
      tex_block_wrap: ['$$', '$$']
  - toc:
      permalink: true

extra_javascript:
  - javascript/config.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  
plugins:
  - literate-nav:
      nav_file: navigation.md
  - search
